// "use client";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import { Inter } from "next/font/google";
import Box from "@mui/material/Box";
import Paper from "@mui/material/Paper";
import Grid from "@mui/material/Grid";

import Header from "../layout/header";
import NavHeader from "../layout/navbar/NavHeader";
const inter = Inter({ subsets: ["latin"] });
const Item = styled(Paper)(({ theme }) => ({
  backgroundColor: theme.palette.mode === "dark" ? "#1A2027" : "#fff",
  ...theme.typography.body2,
  padding: theme.spacing(1),
  textAlign: "center",
  color: theme.palette.text.secondary,
}));
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Box sx={{ flexGrow: 1 }}>
      <Grid container spacing={2}>
        <Grid item xs={8}>
          <Item>xs=8</Item>
        </Grid>
        <Grid item xs={4}>
          <Item>xs=4</Item>
        </Grid>
        <Grid item xs={4}>
          <Item>xs=4</Item>
        </Grid>
        <Grid item xs={8}>
          <Item>xs=8</Item>
        </Grid>
      </Grid>
    </Box>
    // <html lang="en">
    //   <body className={inter.className}>
    //     <Header />
    //     <NavHeader />
    //     {children}
    //   </body>
    // </html>
  );
}
